### ISSUE TITLE
Need to add some animation 

### ISSUE THREAD

**Issue by lilylee1874** [gezellii/design#6]
小飞机fly out when scroll down.

trace:
![trace](https://github.com/gezellii/design/assets/52693877/e2594a64-acbc-461d-b29d-d908a6c1a341)

prototype:
https://www.figma.com/proto/iWgdZefqkOpnzNOKkm0H4T/mapotofu?page-id=234%3A22458&type=design&node-id=234-31782&viewport=299%2C466%2C0.11&scaling=min-zoom&starting-point-node-id=234%3A24007

resource:
![plant](https://github.com/gezellii/design/assets/52693877/f403502c-4121-4192-843b-f1ebe5cf0af8)
![girl 2](https://github.com/gezellii/design/assets/52693877/a9a4cf7f-ccb3-48c2-8747-3df2ddeb0df8)
![girl 3](https://github.com/gezellii/design/assets/52693877/6b54415a-d4b5-4d8c-8396-0bf10125150f)
![girl](https://github.com/gezellii/design/assets/52693877/60bc7074-5f21-491f-af7d-0db1f83055ac)
![paper flight](https://github.com/gezellii/design/assets/52693877/7d8bae0b-e8f9-496d-900f-183275637b30)

**Comment by lilylee1874** [comment]
@wgao19 Can you help to take a look? ❤️

**Comment by wgao19** [comment]
@lilylee1874 take a look at the demo first: http://mapotofu-plane.glitch.me/
Also, what's your thoughts on smaller screens?

**Comment by lilylee1874** [comment]
That's better than I could imagine！
For smaller screen we can set 1200px as the minimum screen to trigger this animation

**Comment by lilylee1874** [comment]
![girl 0](https://github.com/gezellii/design/assets/52693877/7d169ced-5cdc-4854-b0fc-7a14e78d97d1)
![girl 1](https://github.com/gezellii/design/assets/52693877/755baea8-210c-4f53-a25f-d5a553af3a67)
![girl 2](https://github.com/gezellii/design/assets/52693877/611cf5bc-949d-4d47-9bba-dd6a4f51c6e4)

@wgao19 added

**Comment by lilylee1874** [comment]
![gir - static(1)](https://github.com/gezellii/design/assets/52693877/aaf4f522-0309-4511-a62f-7ae32d939587)

**Comment by lilylee1874** [comment]
replace plane image

![paper plane 2](https://github.com/gezellii/design/assets/52693877/84336030-0fd2-4583-afef-b74598e7aef6)

**Comment by lilylee1874** [comment]
the Github hyperlink doesn't work, I feel it's somehow related to the animation. @wgao19 can you help to take a look?

**Comment by lilylee1874** [comment]
> the Github hyperlink doesn't work, I feel it's somehow related to the animation. @wgao19 can you help to take a look?

fixed
